name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PHRASE }}
          script: |
            cd tetris
            sudo rm -rf ./*
            sudo docker container prune -f
            sudo docker image prune -f
            sudo docker compose build --no-cache
            sudo docker compose up
